[profile.dev]
panic = "abort"
[profile.release]
pa = "abort"
[package]
name = "rust_os"
version = "0.1.0"
authors = ["faede <2554622161@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.6.0"